[package]
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9"
hyper = { version = "0.14", features = ["client"] }
hyper-rustls = { version = "0.23" }
log = { version = "0.4" }
noun = { git = "https://github.com/mcevoypeter/noun.git", features = ["thread-safe"] }
rustls = { version = "0.20" }
tokio = { version = "1", features = ["io-std", "io-util"] }

[features]
default = ["multi-thread"]
multi-thread = ["tokio/rt-multi-thread"]

[lib]
crate-type = ["lib", "staticlib"]
