[package]
name = "io"
version = "0.1.0"
edition = "2021"

[dependencies]
bitstream-io = "1.2"
hyper = { version = "0.14", features = ["full"] }
hyper-rustls = "0.23"
noun = { path = "../noun" }
rustls = "0.20"
tokio = { version = "1", features = ["full"] }
